### ISSUE TITLE
Special characters in arguments interfere with command

### ISSUE THREAD

**Issue by uuf6429** [lavie/runlike#38]
Let's say I generated the command for running portainer:

```bash
docker run \
    --detach=true \
    --label traefik.frontend.rule="Host:my.host.com" \
#           ^-------- 1 --------^ ^------- 2 ------^
    portainer/portainer \
    --admin-password \
    $2y$17$P06LST8KwocXXXXXXX
#   ^---------- 3 ----------^
```

1. I noticed that labels and environment variables have their values quoted instead of the whole argument. I'm not sure if this is the best behaviour (what if the label key contains special characters or a space?).
2. Since double quotes are generally used, I also wondered if they could be susceptible to variable expansion, so maybe single quotes should be used instead. This might apply to other places too.
3. Since arguments are not escaped, if they contain special characters they interfere with the generated command.

**Comment by anryko** [comment]
Fixed.
