### ISSUE TITLE
Docker image for v0.5.0 does not contain changes introduced in v0.5.0

### ISSUE THREAD

**Issue by panagiks** [lavie/runlike#40]
Steps to reproduce:

- Create a docker container with a `--log-opt` option
- Run `docker run --rm -v /var/run/docker.sock:/var/run/docker.sock assaflavie/runlike:0.5.0 <name>`
- Notice that `--log-opt` is not in the output

This affects both the `latest` and the `0.5.0` tags.

**Comment by reconman** [comment]
Encountering the same bug with 1.4.4. It actually contains a 1.4.3 python release.
