### ISSUE TITLE
Arm compatible docker image

### ISSUE THREAD

**Issue by s7726** [lavie/runlike#48]
Would love to be able to run the dockerized version on my pi3 based system.

**Comment by capntrips** [comment]
```bash
wget https://raw.githubusercontent.com/lavie/runlike/master/Dockerfile
docker build -t runlike .
docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
    runlike YOUR-CONTAINER
```
Works on my RPi4 running LibreELEC 9.2.3

**Comment by s7726** [comment]
Looking for something already posted to docker hub to avoid that build step on systems without build infrastructure in place.

**Comment by jotka** [comment]
@s7726 it's Docker, so what build infrastructure you mean? :)

**Comment by s7726** [comment]
I don't remember the context for this comment/request 😅.

Maybe some of the thumbs and rockets do?
