### ISSUE TITLE
/etc/hosts file

### ISSUE THREAD

**Issue by passie** [lavie/runlike#7]
if a local hosts file is used these are not propagated into the docker run file.
Would it be possible to include these as well like 
--add-host webserver01:192.168.0.100

**Comment by assaflavie** [comment]
sure. if you want to have a whack at it I'll be happy to merge.

**Comment by passie** [comment]
I created a pull request, but for some reason it's failing. 
Would you mind to have a look ?

**Comment by anryko** [comment]
#41
