### ISSUE TITLE
Broken pypi package

### ISSUE THREAD

**Issue by imlonghao** [lavie/runlike#76]
Hello,

I am packaging runlike to [AUR](https://aur.archlinux.org/packages/python-runlike/)

When I am trying to upgrade runlike from 0.7.0 to 1.0.0, I think the pypi package is broken.

The setup.py file is missing `entry_points` block which results in no `/usr/bin/runlike` is created.

I try to install runlike via pip, also failed.

```
docker run -it --rm python:3.9 /bin/bash
pip install runlike

# runlike
bash: runlike: command not found
```

Thanks.

**Comment by lavie** [comment]
Thanks for reporting this!

Please try now (latest is `1.0.2`) on pypi.

**Comment by lavie** [comment]
Thanks. I'm fixing some more issues and I'll release another patch version today.
